spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
server:
  port: 8080
  shutdown: graceful

catalog:
  page-size: 10
